package bingogame;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class ChooseWinnerScreen extends javax.swing.JFrame {

    /**
     * Creates new form ChooseWinnerScreen
     */
    
    int lang = 0;
    String ttsSpeech = "This game's winner is... ";
    String congrats = "Congratulations, ";
    
    public ChooseWinnerScreen() {
        initComponents();
        Toolkit a = Toolkit.getDefaultToolkit();
        int xSize = (int) a.getScreenSize().getWidth();
        int ySize = (int) a.getScreenSize().getHeight();
        this.setSize(xSize, ySize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        languageButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        nameTextField = new javax.swing.JTextField();
        enterNameText = new javax.swing.JLabel();
        bingoBallJLabel = new javax.swing.JLabel();
        gameTitle = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setLayout(null);

        languageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingogame/usaflag.png"))); // NOI18N
        languageButton.setText("jButton1");
        languageButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        languageButton.setContentAreaFilled(false);
        languageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(languageButton);
        languageButton.setBounds(30, 960, 70, 70);

        confirmButton.setFont(new java.awt.Font("Gameplay", 0, 48)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(51, 204, 0));
        confirmButton.setText("CONFIRM");
        confirmButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton);
        confirmButton.setBounds(800, 860, 390, 120);

        nameTextField.setFont(new java.awt.Font("Gameplay", 0, 24)); // NOI18N
        nameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameTextField.setText("jTextField1");
        nameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTextFieldMouseClicked(evt);
            }
        });
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameTextField);
        nameTextField.setBounds(560, 580, 880, 80);

        enterNameText.setFont(new java.awt.Font("Gameplay", 0, 48)); // NOI18N
        enterNameText.setForeground(new java.awt.Color(255, 255, 255));
        enterNameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterNameText.setText("Enter the name of the winner");
        jPanel1.add(enterNameText);
        enterNameText.setBounds(210, 370, 1590, 160);

        bingoBallJLabel.setFont(new java.awt.Font("Heavitas", 0, 200)); // NOI18N
        bingoBallJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(bingoBallJLabel);
        bingoBallJLabel.setBounds(240, 550, 530, 250);

        gameTitle.setFont(new java.awt.Font("QUARTZO demo", 0, 70)); // NOI18N
        gameTitle.setForeground(new java.awt.Color(255, 255, 255));
        gameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameTitle.setText("CHOOSE WINNER");
        jPanel1.add(gameTitle);
        gameTitle.setBounds(560, 100, 880, 130);

        quitButton.setBackground(new java.awt.Color(51, 51, 255));
        quitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingogame/xbutton.png"))); // NOI18N
        quitButton.setBorder(null);
        quitButton.setBorderPainted(false);
        quitButton.setContentAreaFilled(false);
        quitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitButton.setDefaultCapable(false);
        quitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quitButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/bingogame/xbuttonClick.png"))); // NOI18N
        quitButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bingogame/xbutton.png"))); // NOI18N
        quitButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/bingogame/xbutton.png"))); // NOI18N
        quitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitButtonMouseClicked(evt);
            }
        });
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(quitButton);
        quitButton.setBounds(1880, 10, 32, 34);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingogame/Blue Checkerboard.png"))); // NOI18N
        backGround.setText("jLabel2");
        jPanel1.add(backGround);
        backGround.setBounds(0, 0, 1920, 1080);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2007, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_quitButtonMouseClicked

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitButtonActionPerformed

    private void nameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTextFieldMouseClicked
        // TODO add your handling code here:
        nameTextField.setText("");

    }//GEN-LAST:event_nameTextFieldMouseClicked

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        
        GUI gui = new GUI();
        
        
        String name = nameTextField.getText();
        JLabel congratsMessage = new JLabel("Congratulations,   " + name + "!");
        congratsMessage.setFont(new Font("Provicali", Font.PLAIN, 18));
        
        
        textToSpeech(ttsSpeech + name);
        
        
        JOptionPane.showMessageDialog(this, 
        "<html><font face='Provocali' size='15' color='black'>" + congrats  + "<html><font face='Calibri' size='15' color='blue'>" + name + "<html><font face='Provocali' size='15' color='black'>!", "Winner", JOptionPane.PLAIN_MESSAGE);
        
        gui.show();
        dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void languageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageButtonActionPerformed
        // TODO add your handling code here:
        lang++;

        switch (lang){
            case 0: {
                gameTitle.setText("CHOOSE WINNER");
                enterNameText.setText("ENTER THE NAME OF THE WINNER");
                confirmButton.setText("CONFIRM");
                ttsSpeech = "This Bingo's winner is... ";
                congrats = "Congratulations, ";
                languageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingogame/usaflag.png")));
                break;
            }

            case 1: {
                gameTitle.setText("ELEGIR GANADOR");
                enterNameText.setText("INTRODUZCA EL NOMBRE DEL GANADOR");
                confirmButton.setText("CONFIRMAR");
                ttsSpeech = "El ganador de este bingo es ... ";
                congrats = "Felicidades, ";
                languageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingogame/spanishflag.png")));
                break;
            }

            case 2:{
                gameTitle.setText("ESCOLHA VENCEDOR");
                enterNameText.setText("DIGITE O NOME DO GANHADOR");
                confirmButton.setText("CONFIRME");
                ttsSpeech = "O vencedor deste Bingo é... ";
                congrats = "Parabéns, ";
                languageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingogame/brazilflag.png")));
                break;
            }

            default:{
                lang = -1;
                gameTitle.setText("CHOISISSEZ GAGNANT");
                enterNameText.setText("ENTRER LE NOM DU GAGNANT");
                confirmButton.setText("CONFIRMER");
                ttsSpeech = "Le gagnant de ce Bingo est... ";
                congrats = "Félicitations, ";
                languageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bingogame/frenchflag.png")));
                break;
            }
        }

    }//GEN-LAST:event_languageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseWinnerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseWinnerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseWinnerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseWinnerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseWinnerScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel bingoBallJLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel enterNameText;
    private javax.swing.JLabel gameTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton languageButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables

public static void textToSpeech(String words){
        VoiceManager freeVM;
        Voice voice;
        
        System.setProperty("freetts.voices", "com.sun.speech.freetts.en.us.cmu_us_kal.KevinVoiceDirectory");
        voice = VoiceManager.getInstance().getVoice("kevin16");    
    
        if (voice != null) {
        voice.allocate();// Allocating Voice
        try {
            voice.setRate(130);// Setting the rate of the voice
            voice.setPitch(100);// Setting the Pitch of the voice
            voice.setVolume(3);// Setting the volume of the voice
            voice.speak(words);// Calling speak() method

        } catch (Exception e1) {
        }

    } else {
        throw new IllegalStateException("Cannot find voice: kevin16");
    }
}



}



    
